#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
sudo service status nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx start
