#!/usr/bin/env bash
# Install nginx and add a custom http response header

# Updating Packages and Installing nginx web server
sudo apt update
sudo apt install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a Moved Permanently Redirection (301)
replacement_string_301="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replacement_string_301/" /etc/nginx/sites-enabled/default

# Creating 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_string_404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_string_404/" /etc/nginx/sites-enabled/default

# Configure custom http response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing nginx configrations for syntax errors
sudo nginx -t

# Restart nginx service after configrations changes
sudo service nginx restart
