#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server so that it send traffic to web-01 and web-02
sudo apt-get update
sudo apt-get install haproxy -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 197495-web-01 54.81.251.18:80 check
        server 197495-web-02 54.237.36.12:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
